# 도형 그리기
이미지에서 match 가 되는 영역 표시 등, 사용자가 결과를 인식하기 쉽게 함
## Line 그리기


In [4]:
import numpy as np
import cv2

In [5]:
img = np.zeros((512,512,3), np.uint8) # 검정색 canvas
img = cv2.line(img, (0,0), (511,511), (255,0,0), 5)

`cv2.line(img, start end, color, thickness)`
- img : 그림을 그릴 파일
- start : 시작 좌표
- end : 종료 좌표
- color : BGR 형태의 color (255, 0, 0) => blue
- thickness : 선 두께(픽셀)

In [12]:
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1

## 사각형 그리기
왼쪽 위와 오른쪽 아래 점을 연결하는 사각형

`cv2.rectangle(img, start, end, color, thickness)`

In [7]:
img = cv2.rectangle(img, (384,0), (510,128), (0,255,0), 3)

## 원 그리기
`cv2.circle(img, center, radian, color, thickness)`

In [8]:
img = cv2.circle(img, (447,63), 63, (0,0,255), -1)
# thickness 가 -1이면 원 안쪽을 채운다

## 타원 그리기
`cv2.ellipse(img, center, axes, angle, startAngle, endAngle, color, thickness)`
- axes : 중심에서 가장 큰 거리와 작은 거리
- angle : 타원의 기울기 각
- startAngle : 타원의 시작 각도
- endAngle : 타원이 끝나는 각도

In [9]:
img = cv2.ellipse(img, (256,256), (100,50), 0, 0, 180, 255, -1)

## 폴리곤 그리기
`cv2.polylines(img, pts, isClosed, color, thickness)`

- pts : 연결할 꼭지점 좌표
- isClosed : 닫힌 도형 여부

In [10]:
pts = np.array([[10,5], [20,30], [70,20], [50,10]], np.int32)
# 각 꼭지점은 2차원 행렬
# 이미지에 표현하기위해 3차원 행렬로 변환
pts = pts.reshape((-1,1,2))
print(pts)
img = cv2.polylines(img, [pts], True, (0,255,255))

[[[10  5]]

 [[20 30]]

 [[70 20]]

 [[50 10]]]


## Text 추가

`cv2.putText(img,text,org,font,fontScale,color)`

- text : 표시할 문자열
- org : 문자열이 표시될 위치
- font : font type. CV2.FONT_XXX 로 표시
- fontScale : 폰트 사이즈

In [11]:
img = cv2.putText(img, 'OpenCV', (10, 500), cv2.FONT_HERSHEY_SIMPLEX, 4, (255,255,255), 2)