# 이미지 연산

## 이미지 더하기
방법이 총 두 가지
`cv2.add()` : Saturation 연산 (범위 밖 값은 모두 한계값으로 설정)

`img1 + img2` : Modulo 연산 (한계 값으로 나눈 나머지로 연산)


## 이미지 Blending

이미지에 가중치를 두어 합치는 방법

In [1]:
import cv2
import numpy as np

In [11]:
img1 = cv2.imread("Images/Sample_mili.jpg")
img2 = cv2.imread("Images/Sample_mili2.jpg")

In [8]:
def nothing(x):
    pass

In [18]:
cv2.namedWindow("image")
cv2.createTrackbar('W', 'image', 0, 100, nothing)

while True:
    
    w = cv2.getTrackbarPos('W', 'image')
    
    dst = cv2.addWeighted(img1, float(100 - w) * 0.01 , img2, float(w) * 0.01, 0)
    
    cv2.imshow('dst', dst)
    
    if cv2.waitKey(1) &0xFF == 27:
        break
        
cv2.destroyAllWindows()
cv2.waitKey(1)
    

-1

## 비트연산
AND OR NOT XOR 연산

이미지에서 바탕을 제거하고 이미지에 추가하는 예시

In [19]:
import cv2
import numpy as np

In [88]:
img1 = cv2.imread("Images/Sample_mili.jpg")
img2 = cv2.imread("Images/Sample_mili3.jpg")

In [89]:
# 삽입할 이미지의 정보
rows, cols, channels = img1.shape

In [90]:
roi = img2[0:rows, 0:cols]

In [92]:
# mask 를 만든다.
img2gray = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
print(img2gray)
#다음 챕터에서 다루는 내용|
ret, mask = cv2.threshold(img2gray, 96 , 255, cv2.THRESH_BINARY)
mask_inv = cv2.bitwise_not(mask)

[[96 96 96 ... 96 96 96]
 [96 96 96 ... 96 96 96]
 [96 96 96 ... 96 96 96]
 ...
 [96 96 96 ... 96 96 96]
 [96 96 96 ... 96 96 96]
 [96 96 96 ... 96 96 96]]


In [96]:

# 둘다 0이 아닌 경우에만 값을 통과 시킴.
# mask 이외의 영역을 모두 제거함
# https://copycoding.tistory.com/156
img1_fg = cv2.bitwise_or(img1, img1, mask=mask)
img2_bg = cv2.bitwise_and(roi, roi, mask=mask_inv)

# 2개의 이미지를 합치면 바탕은 제거된 채 logo 부분만.
dst = cv2.add(img1_fg, img2_bg)

# 합쳐진 이미지를 원본에 추가
img2[0:rows, 0:cols] = dst

In [99]:
cv2.imshow('res', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.waitKey(1)

-1